<a href="https://colab.research.google.com/github/MuraliKoushikDesu/MuraliKoushikDesu/blob/main/muralikoushikdesu_icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a random vector of size 15 with integers in the range 1-20
vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
reshaped_array = vector.reshape(3, 5)

# Print the shape of the array
print("Array shape:", reshaped_array.shape)

# Replace the maximum value in each row with 0
reshaped_array[np.arange(reshaped_array.shape[0]), np.argmax(reshaped_array, axis=1)] = 0

# Print the modified array
print("Modified array:")
print(reshaped_array)


Array shape: (3, 5)
Modified array:
[[ 5  3  0 14  1]
 [ 0  8 10 14  1]
 [11 16  7 11  0]]


In [ ]:
import numpy as np

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array = np.empty((4, 3), dtype=np.int32)

# Print the shape of the array
print("Array shape:", array.shape)

# Print the type of the array
print("Array type:", type(array))

# Print the data type of the array
print("Array data type:", array.dtype)


Array shape: (4, 3)
Array type: <class 'numpy.ndarray'>
Array data type: int32


In [ ]:
import numpy as np

# Create the given array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(array)

# Print the sum of the diagonal elements
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [ ]:
import numpy as np

# Create an array of odd numbers between 10 to 70
odd_array = np.arange(11, 71, 2)

# Create an array of even numbers between 10 to 70
even_array = np.arange(10, 71, 2)

# Print the arrays
print("Odd numbers array:", odd_array)
print("Even numbers array:", even_array)


Odd numbers array: [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Even numbers array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]


In [ ]:
import numpy as np

# Create two arrays of the same size
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise power operation
power = np.power(array1, array2)

# Print the results
print("Addition:", addition)
print("Multiplication:", multiplication)
print("Power:", power)


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Power: [  1  32 729]


In [ ]:
import numpy as np

# Create the given array
array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

# Sort the array by row in ascending order
sorted_by_row = np.sort(array, axis=1)

# Sort the array by column in ascending order
sorted_by_column = np.sort(array, axis=0)

# Print the sorted arrays
print("Sorted by row:")
print(sorted_by_row)
print("Sorted by column:")
print(sorted_by_column)


Sorted by row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [ ]:
import numpy as np

# Declare the given array
array = np.array([[4, 2, np.nan, 1],
                  [11, 12, 14, 9],
                  [5, np.nan, 1, np.nan]])

# Find missing data by returning a Boolean output
missing_data = np.isnan(array)

# Print the Boolean output
print(missing_data)


[[False False  True False]
 [False False False False]
 [False  True False  True]]
